import { useEffect, useState } from 'react'
import axios from 'axios'
import { Link } from 'react-router-dom'
import { ArrowRight, Check, Clock3, PackageCheck, Star } from 'lucide-react'
import Rating from '../components/Rating'
import { resolveProductImage } from '../lib/images'

const statusTone = (status) => status === 'Delivered' ? 'bg-[#e8f3ec] text-[#2f7d4a]' : status === 'Cancelled' ? 'bg-[#fff0ef] text-[#b64437]' : 'bg-[#fff4dc] text-[#a66b0b]'

const UserOrders = () => {
  const [orders, setOrders] = useState([])
  const [loading, setLoading] = useState(true)
  useEffect(() => { const load = async () => { try { const user = JSON.parse(localStorage.getItem('urbanhive_user')); const { data } = await axios.get(`${import.meta.env.VITE_API_BASE_URL}/api/users/order-history/${user?.id}`); setOrders(data) } finally { setLoading(false) } }; load() }, [])
  if (loading) return <div className="page-shell py-10"><div className="h-56 animate-pulse rounded-[26px] bg-[#eee8dd]" /></div>
  if (!orders.length) return <div className="page-shell py-16 text-center"><PackageCheck className="mx-auto h-12 w-12 text-[#2f7d4a]" /><h1 className="mt-4 text-3xl font-extrabold">No orders yet</h1><Link to="/customer/vendors" className="mt-5 inline-flex items-center gap-1 font-bold text-[#e86f32]">Explore stores <ArrowRight className="h-4 w-4" /></Link></div>
  return <div className="min-h-screen bg-[#faf8f3] pb-14"><div className="page-shell py-8 sm:py-10"><p className="text-xs font-bold uppercase tracking-[.15em] text-[#2f7d4a]">Order history</p><h1 className="mt-1 text-3xl font-extrabold tracking-[-.04em]">Your orders</h1><div className="mt-7 space-y-5">{orders.map((order) => <article key={order._id} className="rounded-[22px] border border-[#ebe5d9] bg-white p-5 sm:p-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><p className="text-sm font-extrabold">Order #{order._id.slice(-6).toUpperCase()}</p><p className="mt-1 text-xs font-medium text-[#697168]">{new Date(order.createdAt).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })} · {order.products.length} item{order.products.length > 1 ? 's' : ''}</p></div><span className={`w-fit rounded-full px-3 py-1.5 text-xs font-bold ${statusTone(order.orderStatus)}`}>{order.orderStatus}</span></div><div className="mt-5 flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full bg-[#2f7d4a]" /><span className="h-0.5 flex-1 bg-[#2f7d4a]" /><span className="h-2.5 w-2.5 rounded-full bg-[#2f7d4a]" /><span className="h-0.5 flex-1 bg-[#2f7d4a]" /><span className={`h-2.5 w-2.5 rounded-full ${order.orderStatus === 'Delivered' ? 'bg-[#2f7d4a]' : 'bg-[#d7ddd4]'}`} /></div><div className="mt-2 flex justify-between text-[11px] font-bold text-[#697168]"><span>Placed</span><span>Packed</span><span>{order.orderStatus === 'Delivered' ? 'Delivered' : order.orderStatus}</span></div><div className="mt-5 flex flex-wrap gap-3">{order.products.filter((item) => item.productId).map((item) => <Link key={item.productId._id} to={`/customer/view-product/${item.productId._id}`} className="flex items-center gap-2 rounded-xl bg-[#f7f4ed] p-2 pr-3"><img src={resolveProductImage(item.productId.image)} alt="" className="h-10 w-10 rounded-lg object-cover" /><span className="max-w-28 truncate text-xs font-bold">{item.productId.name}</span>{item.quantity > 1 && <span className="text-xs text-[#697168]">×{item.quantity}</span>}</Link>)}</div><div className="mt-5 flex flex-col gap-3 border-t border-[#eee8dd] pt-4 sm:flex-row sm:items-center sm:justify-between"><p className="text-lg font-extrabold">₹{order.totalAmount}</p><div className="flex items-center gap-3">{order.orderStatus === 'Delivered' && <Rating rating={order.rating} orderId={order._id} />}<Link to="/customer/vendors" className="text-sm font-bold text-[#e86f32]">Order again</Link></div></div></article>)}</div></div></div>
}
export default UserOrders
