import { useEffect, useState } from 'react'
import { PackageOpen } from 'lucide-react'
import OrderProductsModal from '../components/OrderProductsModal'

const VendorOrders = () => {
  const [orders, setOrders] = useState([])
  const [selectedOrder, setSelectedOrder] = useState(null)
  useEffect(() => { const load = async () => { const vendor = JSON.parse(localStorage.getItem('urbanhive_user')); const token = localStorage.getItem('urbanhive_token'); try { const response = await fetch(`${import.meta.env.VITE_API_BASE_URL}/api/vendors/get-orders/${vendor?._id}`, { headers: { Authorization: `Bearer ${token}` } }); setOrders(await response.json()) } catch { setOrders([]) } }; load() }, [])
  const tone = (status) => status === 'Delivered' ? 'bg-[#e8f3ec] text-[#2f7d4a]' : status === 'Pending' ? 'bg-[#fff4dc] text-[#a66b0b]' : 'bg-[#e8eef8] text-[#4775b6]'
  return <div className="min-h-full bg-[#faf8f3]"><div className="mx-auto max-w-[1280px] py-3"><div className="rounded-[26px] border border-[#e7e4dd] bg-[#f4eadb] p-7"><p className="text-xs font-bold uppercase tracking-[.15em] text-[#2f7d4a]">Fulfilment</p><h1 className="mt-2 text-3xl font-extrabold tracking-[-.04em]">Incoming orders</h1><p className="mt-2 text-sm text-[#697168]">Stay on top of every local delivery.</p></div><div className="mt-6 overflow-hidden rounded-2xl border border-[#ebe5d9] bg-white">{orders.length ? <div className="divide-y divide-[#eee8dd]">{orders.map((order) => <button key={order._id} onClick={() => setSelectedOrder(order)} className="grid w-full grid-cols-[1fr_auto] gap-3 p-5 text-left transition hover:bg-[#faf8f3] sm:grid-cols-[1.2fr_1fr_1fr_auto]"><div><p className="font-extrabold">#{order._id.slice(-6).toUpperCase()}</p><p className="mt-1 text-xs text-[#697168]">{new Date(order.createdAt).toLocaleDateString()}</p></div><p className="hidden self-center text-sm font-semibold text-[#697168] sm:block">{order.products?.length || 0} items</p><p className="self-center font-extrabold">₹{order.totalAmount}</p><span className={`self-center rounded-full px-3 py-1.5 text-xs font-bold ${tone(order.orderStatus)}`}>{order.orderStatus}</span></button>)}</div> : <div className="p-12 text-center"><PackageOpen className="mx-auto h-9 w-9 text-[#2f7d4a]" /><p className="mt-3 font-bold">No orders yet</p></div>}</div></div>{selectedOrder && <OrderProductsModal isOpen={true} onClose={() => setSelectedOrder(null)} order={selectedOrder} />}</div>
}
export default VendorOrders
