import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import axios from 'axios'
import { ArrowRight, Package, Plus, ShoppingBag, Star, Users } from 'lucide-react'
import { useAuth } from '../context/AuthContext'

const VendorDashboard = () => {
  const [stats, setStats] = useState(null)
  const { user } = useAuth()
  useEffect(() => { const load = async () => { try { const vendor = JSON.parse(localStorage.getItem('urbanhive_user')); const { data } = await axios.get(`${import.meta.env.VITE_API_BASE_URL}/api/vendors/dashboard/${vendor?.id || vendor?._id}`); setStats(data) } catch { setStats({ totalOrders: 0, totalProducts: 0, totalUsers: 0, totalRevenue: 0, averageRating: 0 }) } }; load() }, [])
  if (!stats) return <div className="page-shell py-10"><div className="h-64 animate-pulse rounded-[26px] bg-[#eee8dd]" /></div>
  const cards = [{ label: 'Revenue', value: `₹${Number(stats.totalRevenue || 0).toLocaleString()}`, icon: ShoppingBag, tone: 'bg-[#fff0e7] text-[#e86f32]' }, { label: 'Orders', value: stats.totalOrders, icon: Package, tone: 'bg-[#e8f3ec] text-[#2f7d4a]' }, { label: 'Products', value: stats.totalProducts, icon: Users, tone: 'bg-[#e8eef8] text-[#4775b6]' }, { label: 'Rating', value: Number(stats.averageRating || 0).toFixed(1), icon: Star, tone: 'bg-[#fff4dc] text-[#d28a13]' }]
  return <div className="min-h-full bg-[#faf8f3]"><div className="mx-auto max-w-[1280px] py-3"><section className="rounded-[26px] bg-[#182018] px-7 py-8 text-white sm:px-10"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><p className="text-sm font-bold text-[#a8d5b4]">Store overview</p><h1 className="mt-1 text-3xl font-extrabold tracking-[-.04em]">Good morning, {user?.storeName || user?.name || 'there'}.</h1><p className="mt-2 text-sm text-white/65">Here’s what’s happening with your store today.</p></div><Link to="/vendor/add-product" className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#e86f32] px-4 py-3 text-sm font-bold hover:bg-[#c95722]"><Plus className="h-4 w-4" /> Add product</Link></div></section><section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map(({ label, value, icon: Icon, tone }) => <div key={label} className="rounded-2xl border border-[#ebe5d9] bg-white p-5"><span className={`flex h-10 w-10 items-center justify-center rounded-xl ${tone}`}><Icon className="h-5 w-5" /></span><p className="mt-5 text-sm font-bold text-[#697168]">{label}</p><p className="mt-1 text-2xl font-extrabold text-[#182018]">{value}</p></div>)}</section><section className="mt-6 grid gap-4 lg:grid-cols-2"><Link to="/vendor/orders" className="group rounded-2xl border border-[#ebe5d9] bg-white p-6 hover:shadow-lg"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#2f7d4a]">Manage fulfilment</p><h2 className="mt-2 text-xl font-extrabold">Review incoming orders</h2><p className="mt-2 text-sm text-[#697168]">Track new, active, and delivered orders in one place.</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-[#e86f32]">View orders <ArrowRight className="h-4 w-4" /></span></Link><Link to="/vendor/home" className="group rounded-2xl border border-[#ebe5d9] bg-white p-6 hover:shadow-lg"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#2f7d4a]">Your catalogue</p><h2 className="mt-2 text-xl font-extrabold">Manage your products</h2><p className="mt-2 text-sm text-[#697168]">Update pricing, product details, and availability.</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-[#e86f32]">Open products <ArrowRight className="h-4 w-4" /></span></Link></section></div></div>
}
export default VendorDashboard
