import { useEffect, useState } from 'react'
import axios from 'axios'
import { LocateFixed, MapPin } from 'lucide-react'
import { Button } from '../components/ui/button'
import { Input } from '../components/ui/input'
import { Label } from '../components/ui/label'
import { useToast } from '../hooks/use-toast'

const categories = ['Grocery', 'Clothing', 'Sports Goods', 'Furniture', 'Electronics', 'Books', 'Beauty & Personal Care', 'Toys & Games', 'Home Appliances', 'Automotive', 'Health & Wellness', 'Jewelry', 'Pet Supplies', 'Others']
const VendorSettingsPage = () => {
  const { toast } = useToast()
  const [form, setForm] = useState({ storeName: '', storeAddress: '', phone: '', category: '', latitude: '', longitude: '' })
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  useEffect(() => { axios.get(`${import.meta.env.VITE_API_BASE_URL}/api/vendors/profile`).then(({ data }) => setForm({ storeName: data.storeName || '', storeAddress: data.storeAddress || '', phone: data.phone || '', category: data.category || '', latitude: data.location?.coordinates?.[1]?.toString() || '', longitude: data.location?.coordinates?.[0]?.toString() || '' })).catch(() => toast({ title: 'Could not load store settings', variant: 'destructive' })).finally(() => setLoading(false)) }, [])
  const update = (event) => setForm((data) => ({ ...data, [event.target.name]: event.target.value }))
  const locate = () => { if (!navigator.geolocation) return toast({ title: 'Location is not supported by this browser', variant: 'destructive' }); navigator.geolocation.getCurrentPosition(({ coords }) => setForm((data) => ({ ...data, latitude: coords.latitude.toFixed(6), longitude: coords.longitude.toFixed(6) })), () => toast({ title: 'Allow location permission to update the store pin', variant: 'destructive' })) }
  const submit = async (event) => { event.preventDefault(); if (!form.storeName || !form.storeAddress || !form.phone || !form.category) return toast({ title: 'Complete all store details', variant: 'destructive' }); setSaving(true); try { const location = form.latitude && form.longitude ? { type: 'Point', coordinates: [Number(form.longitude), Number(form.latitude)] } : undefined; await axios.put(`${import.meta.env.VITE_API_BASE_URL}/api/vendors/update`, { storeName: form.storeName, storeAddress: form.storeAddress, phone: form.phone, category: form.category, location }); toast({ title: 'Store settings saved' }) } catch { toast({ title: 'Could not save store settings', variant: 'destructive' }) } finally { setSaving(false) } }
  if (loading) return <div className="h-72 animate-pulse rounded-[26px] bg-[#eee8dd]" />
  return <div className="min-h-full bg-[#faf8f3]"><div className="mx-auto max-w-2xl py-3"><section className="rounded-[26px] border border-[#e7e4dd] bg-white p-6 sm:p-8"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#2f7d4a]">Your business</p><h1 className="mt-2 text-3xl font-extrabold">Store settings</h1><p className="mt-2 text-sm text-[#697168]">Keep your storefront details and delivery pin accurate.</p><form onSubmit={submit} className="mt-7 space-y-5"><div className="grid gap-5 sm:grid-cols-2"><div><Label>Store name</Label><Input name="storeName" value={form.storeName} onChange={update} className="mt-1.5 rounded-xl" /></div><div><Label>Phone number</Label><Input name="phone" value={form.phone} onChange={update} className="mt-1.5 rounded-xl" /></div></div><div><Label>Category</Label><select name="category" value={form.category} onChange={update} className="mt-1.5 h-10 w-full rounded-xl border border-input bg-background px-3 text-sm">{categories.map((category) => <option key={category}>{category}</option>)}</select></div><div><Label>Store address</Label><textarea name="storeAddress" value={form.storeAddress} onChange={update} className="mt-1.5 min-h-24 w-full rounded-xl border border-input p-3 text-sm" /></div><div className="rounded-2xl bg-[#e8f3ec] p-4"><div className="flex items-start justify-between gap-3"><div><p className="flex items-center gap-1.5 text-sm font-extrabold text-[#2f7d4a]"><MapPin className="h-4 w-4" /> Store location</p><p className="mt-1 text-xs text-[#566056]">Use this while you are at the store to update its delivery pin.</p></div><Button type="button" size="sm" onClick={locate} className="rounded-xl"><LocateFixed className="mr-1 h-3.5 w-3.5" /> Update pin</Button></div><p className="mt-3 text-xs font-medium text-[#566056]">{form.latitude && form.longitude ? `Pinned at ${form.latitude}, ${form.longitude}` : 'No location pin set.'}</p></div><Button type="submit" disabled={saving} className="w-full rounded-xl">{saving ? 'Saving…' : 'Save store settings'}</Button></form></section></div></div>
}
export default VendorSettingsPage
